const functions = require("firebase-functions/v1");
const admin = require("firebase-admin");

// Initialize Firebase only if it hasn't been initialized already
if (!admin.apps.length) {
  admin.initializeApp();
}

const db = admin.firestore();
const { VertexAI } = require("@google-cloud/vertexai");

// Vertex AI setup
const vertexAI = new VertexAI({
  project: 'promgn-in',
  location: 'us-central1'
});

const model = vertexAI.preview.getGenerativeModel({
  model: "gemini-1.5-pro",
  generationConfig: {
    maxOutputTokens: 2048,
    temperature: 0.9,
  },
});

exports.generateAIQuestion = functions.https.onCall(async (data, context) => {
  // Check authentication
  if (!context.auth) {
    throw new functions.https.HttpsError(
      "unauthenticated",
      "The function must be called while authenticated."
    );
  }

  const userId = data.userId || context.auth.uid;
  if (!userId) {
    throw new functions.https.HttpsError(
      "invalid-argument", 
      "userId is required."
    );
  }

  try {
    const interactionsRef = db.collection("conversations")
      .doc(userId)
      .collection("interactions");
    const snapshot = await interactionsRef.orderBy("timestamp", "desc").limit(5).get();

    if (snapshot.empty) {
      throw new functions.https.HttpsError(
        "not-found", 
        "No interactions found for this user."
      );
    }

    const interactions = snapshot.docs.map(doc => {
      const d = doc.data();
      return {
        question: d.question,
        answer: d.answer,
        emotion: d.emotion,
        timeToStart: d.timeToStart,
        responseTime: d.responseTime,
      };
    });

    const prompt = `You are a friendly AI helper tasked with helping users who feel stuck in life. Review the user's chat memory below to understand their past interactions, interests, goals, or challenges. Ask one concise, open-ended follow-up question to deepen your understanding of their **current situation**, such as their daily routine, environment, or immediate challenges, focusing on what defines their present circumstances or what’s holding them back. Ensure the question is engaging, specific, and relevant to their past interactions. Avoid repeating questions they’ve already answered by checking the chat memory for topics like current situation, finances, mindset, goals, or weaknesses. If no relevant memory exists or the current situation hasn’t been covered, ask a question to explore their present life or immediate barriers to progress.

    User chat memory:
    ${interactions.map((i, idx) => `Q${idx+1}: ${i.question}\nA${idx+1}: ${i.answer}\n`).join("\n")}
    
    Provide only the question, keeping it simple, specific, and tailored to guide them toward clarity or action.
`;

    const result = await model.generateContent({
      contents: [{role: "user", parts: [{text: prompt}]}],
    });

    const response = result.response;
    if (!response || !response.candidates || !response.candidates[0]) {
      throw new Error("Invalid response from AI model");
    }

    const aiQuestion = response.candidates[0].content.parts[0]?.text?.trim();
    if (!aiQuestion) {
      throw new Error("No question generated by AI");
    }

    await db.collection("conversations").doc(userId).set({
      aiQuestion: aiQuestion,
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    }, {merge: true});

    return {success: true, question: aiQuestion};
  } catch (error) {
    console.error("Error generating AI question:", error);
    throw new functions.https.HttpsError(
      "internal", 
      error.message || "Failed to generate question"
    );
  }
});