const functions = require("firebase-functions/v1");
const admin = require("firebase-admin");

// Initialize Firebase only if it hasn't been initialized already
if (!admin.apps.length) {
  admin.initializeApp();
}

const db = admin.firestore();
const { VertexAI } = require("@google-cloud/vertexai");

// Vertex AI setup
const vertexAI = new VertexAI({
  project: 'promgn-in',
  location: 'us-central1'
});

const model = vertexAI.preview.getGenerativeModel({
  model: "gemini-1.5-pro",
  generationConfig: {
    maxOutputTokens: 2048,
    temperature: 0.9,
  },
});

exports.generateAIhinQuestion = functions.https.onCall(async (data, context) => {
  // Check authentication
  if (!context.auth) {
    throw new functions.https.HttpsError(
      "unauthenticated",
      "The function must be called while authenticated."
    );
  }

  const userId = data.userId || context.auth.uid;
  if (!userId) {
    throw new functions.https.HttpsError(
      "invalid-argument", 
      "userId is required."
    );
  }

  try {
    const interactionsRef = db.collection("conversations")
      .doc(userId)
      .collection("interactions");
    const snapshot = await interactionsRef.orderBy("timestamp", "desc").limit(5).get();

    if (snapshot.empty) {
      throw new functions.https.HttpsError(
        "not-found", 
        "No interactions found for this user."
      );
    }

    const interactions = snapshot.docs.map(doc => {
      const d = doc.data();
      return {
        question: d.question,
        answer: d.answer,
        emotion: d.emotion,
        timeToStart: d.timeToStart,
        responseTime: d.responseTime,
      };
    });

    const prompt = `आप एक मित्रवत AI सहायक हैं जिसका कार्य उन उपयोगकर्ताओं की मदद करना है जो जीवन में फंसे हुए महसूस कर रहे हैं। उपयोगकर्ता की पिछली बातचीत, रुचियों, लक्ष्यों या चुनौतियों को समझने के लिए उनकी चैट मेमोरी की समीक्षा करें। उनकी **वर्तमान स्थिति** को बेहतर समझने के लिए एक संक्षिप्त, खुला सवाल पूछें — जैसे उनकी दैनिक दिनचर्या, वातावरण, या मौजूदा समस्याएं। सवाल ऐसा हो जो उनके वर्तमान हालात या उन्हें आगे बढ़ने से रोकने वाली बाधाओं को उजागर करे।

चैट मेमोरी की जांच करें और अगर उन्होंने पहले से किसी विषय (जैसे वर्तमान स्थिति, वित्त, सोच, लक्ष्य, या कमजोरियां) का उत्तर दिया है तो उसे दोहराएं नहीं। अगर कोई प्रासंगिक मेमोरी नहीं है या वर्तमान स्थिति स्पष्ट नहीं है, तो उनके जीवन की मौजूदा स्थिति या तत्काल बाधाओं को जानने के लिए एक उपयुक्त सवाल पूछें।

    उपयोगकर्ता की चैट मेमोरी:
    ${interactions.map((i, idx) => `Q${idx+1}: ${i.question}\nA${idx+1}: ${i.answer}\n`).join("\n")}

    केवल एक सवाल पूछें जो सरल, विशिष्ट हो और उन्हें स्पष्टता या कार्रवाई की ओर मार्गदर्शित करे।
`;


    const result = await model.generateContent({
      contents: [{role: "user", parts: [{text: prompt}]}],
    });

    const response = result.response;
    if (!response || !response.candidates || !response.candidates[0]) {
      throw new Error("Invalid response from AI model");
    }

    const aiQuestion = response.candidates[0].content.parts[0]?.text?.trim();
    if (!aiQuestion) {
      throw new Error("No question generated by AI");
    }

    await db.collection("conversations").doc(userId).set({
      aiQuestion: aiQuestion,
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    }, {merge: true});

    return {success: true, question: aiQuestion};
  } catch (error) {
    console.error("Error generating AI question:", error);
    throw new functions.https.HttpsError(
      "internal", 
      error.message || "Failed to generate question"
    );
  }
});