const functions = require("firebase-functions/v1");
const admin = require("firebase-admin");

// Initialize Firebase only if it hasn't been initialized already
if (!admin.apps.length) {
  admin.initializeApp();
}

const db = admin.firestore();
const { VertexAI } = require("@google-cloud/vertexai");

// Vertex AI setup
const vertexAI = new VertexAI({
  project: 'promgn-in',
  location: 'us-central1'
});

const model = vertexAI.preview.getGenerativeModel({
  model: "gemini-1.5-pro",
  generationConfig: {
    maxOutputTokens: 2048,
    temperature: 0.9,
  },
});

exports.generateAImalQuestion = functions.https.onCall(async (data, context) => {
  // Check authentication
  if (!context.auth) {
    throw new functions.https.HttpsError(
      "unauthenticated",
      "The function must be called while authenticated."
    );
  }

  const userId = data.userId || context.auth.uid;
  if (!userId) {
    throw new functions.https.HttpsError(
      "invalid-argument", 
      "userId is required."
    );
  }

  try {
    const interactionsRef = db.collection("conversations")
      .doc(userId)
      .collection("interactions");
    const snapshot = await interactionsRef.orderBy("timestamp", "desc").limit(5).get();

    if (snapshot.empty) {
      throw new functions.https.HttpsError(
        "not-found", 
        "No interactions found for this user."
      );
    }

    const interactions = snapshot.docs.map(doc => {
      const d = doc.data();
      return {
        question: d.question,
        answer: d.answer,
        emotion: d.emotion,
        timeToStart: d.timeToStart,
        responseTime: d.responseTime,
      };
    });

    const prompt = `നീ ജീവനിൽ കുടുങ്ങിയിരിക്കുകയാണെന്ന് തോന്നുന്ന ഉപയോക്താക്കളെ സഹായിക്കാൻ നിയോഗിച്ച ഒരു സൗഹൃദ AI സഹായി ആകുകയാണ്. ഉപയോക്താവിന്റെ ചാറ്റ് മെമ്മറി പരിശോധിച്ച് അവരുടെ കഴിഞ്ഞ ഇടപെടലുകൾ, ആസക്തികൾ, ലക്ഷ്യങ്ങൾ, അല്ലെങ്കിൽ വെല്ലുവിളികൾ മനസിലാക്കുക. അവരുടെ **നിലവിലെ സാഹചര്യങ്ങളെക്കുറിച്ച്** വിശദമായി മനസ്സിലാക്കാൻ ഒരു ചുരുക്കവും തുറന്നതുമായ പിന്തുടര്‍ന്നുള്ള ചോദ്യം ചോദിക്കൂ — ഉദാഹരണത്തിന് അവരുടെ ദിനചര്യ, പരിസ്ഥിതി, അല്ലെങ്കിൽ ഉടൻ നേരിടുന്ന വെല്ലുവിളികൾ. ഈ ചോദ്യത്തിൽ അവരുടെ ഇപ്പോഴത്തെ അവസ്ഥയെ നിർവചിക്കുന്ന ഒന്നോ അവരുടെ പുരോഗതിയെ തടയുന്ന ഒന്നോ ആയിരിക്കണം. 

ചാറ്റ് മെമ്മറി പരിശോധിച്ച് അവർ ഇതിനകം ഉത്തരം നൽകിയ വിഷങ്ങളായ നിലവിലെ സാഹചര്യം, സാമ്പത്തികം, മനോഭാവം, ലക്ഷ്യങ്ങൾ, അല്ലെങ്കിൽ ദൗർബല്യങ്ങൾ ആവർത്തിച്ച് ചോദിക്കരുത്. ഇവയുമായി ബന്ധപ്പെട്ട മെമ്മറി ഇല്ലെങ്കിൽ, അവരുടെ ഇപ്പോഴത്തെ ജീവിതം അല്ലെങ്കിൽ ഉടൻ മുന്നോട്ട് പോവാൻ തടസ്സമായ പ്രശ്നങ്ങൾ മനസ്സിലാക്കാൻ സഹായിക്കുന്ന ഒരു ചോദ്യമാകണം.

    ഉപയോക്താവിന്റെ ചാറ്റ് മെമ്മറി:
    ${interactions.map((i, idx) => `Q${idx+1}: ${i.question}\nA${idx+1}: ${i.answer}\n`).join("\n")}
    
    ചുരുക്കവും വ്യക്തവും വ്യക്തതയിലേക്കോ നടപടിയിലേക്കോ നയിക്കുന്നതുമായ ഒരു ചോദ്യമേ നൽകിയിരിക്കേണ്ടത്.
`;


    const result = await model.generateContent({
      contents: [{role: "user", parts: [{text: prompt}]}],
    });

    const response = result.response;
    if (!response || !response.candidates || !response.candidates[0]) {
      throw new Error("Invalid response from AI model");
    }

    const aiQuestion = response.candidates[0].content.parts[0]?.text?.trim();
    if (!aiQuestion) {
      throw new Error("No question generated by AI");
    }

    await db.collection("conversations").doc(userId).set({
      aiQuestion: aiQuestion,
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    }, {merge: true});

    return {success: true, question: aiQuestion};
  } catch (error) {
    console.error("Error generating AI question:", error);
    throw new functions.https.HttpsError(
      "internal", 
      error.message || "Failed to generate question"
    );
  }
});